version: "3.7"
services:
  yaichi:
    image: mtsmfm/yaichi:1.2.0
    ports:
      - 80:3000
      - 35729:35729
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web: &web
    container_name: fragile-window-web
    build:
      context: .
      args:
        - DISABLE_COMPILE=true
    volumes:
      - .:/app:cached
      - tmp:/app/tmp
      - vendor:/vendor
    environment:
      - DATABASE_URL=postgres://postgres:@db
      - PORT=3000
      - HOST=0.0.0.0
      - WEBPACKER_DEV_SERVER_HOST=webpack-dev-server
      - WEBPACKER_DEV_SERVER_PORT=3000
      - WEBPACKER_DEV_SERVER_PUBLIC=fragile-window-webpack-dev-server.localhost
    tty: true
    stdin_open: true
    depends_on:
      - db

  webpack-dev-server:
    <<: *web
    container_name: fragile-window-webpack-dev-server
    command: bin/webpack-dev-server

  db:
    image: postgres:10-alpine
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  vendor:
  tmp:
  db:
